import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:m_galunggung99/_GlobalScript.dart';

class InputListingModel {
  String namepemilik,
      noktppemilik,
      addresspemilik,
      phonepemilik,
      workpemilik,
      employeeID,
      propertyID,
      provinceID,
      cityID,
      kecamatanID,
      kelurahanID,
      postalCodeID,
      addressProperty,
      price,
      isNego,
      lebarjalandepan,
      luastanah,
      luasbangunan,
      statusKunciID,
      bedroom,
      bathroom,
      maidBathroom,
      livingroom,
      dinningroom,
      familyroom,
      kitchen,
      tamanDepan,
      tamanBelakang,
      furnitureID,
      garageID,
      carportID,
      legalityID,
      fcLegalityID,
      listingStatusID,
      useredited;

  InputListingModel(
      {this.namepemilik,
      this.noktppemilik,
      this.addresspemilik,
      this.phonepemilik,
      this.workpemilik,
      this.employeeID,
      this.propertyID,
      this.provinceID,
      this.cityID,
      this.kecamatanID,
      this.kelurahanID,
      this.postalCodeID,
      this.addressProperty,
      this.price,
      this.isNego,
      this.lebarjalandepan,
      this.luastanah,
      this.luasbangunan,
      this.statusKunciID,
      this.bedroom,
      this.bathroom,
      this.maidBathroom,
      this.livingroom,
      this.dinningroom,
      this.familyroom,
      this.kitchen,
      this.tamanDepan,
      this.tamanBelakang,
      this.furnitureID,
      this.garageID,
      this.carportID,
      this.legalityID,
      this.fcLegalityID,
      this.listingStatusID,
      this.useredited});

  factory InputListingModel.postInputListing(Map<String, dynamic> object) {
    return InputListingModel(
        namepemilik: object['namepemilik'],
        noktppemilik: object['noktppemilik'],
        addresspemilik: object['addresspemilik'],
        phonepemilik: object['phonepemilik'],
        workpemilik: object['workpemilik'],
        employeeID: object['employee_id'],
        propertyID: object['property_id'],
        provinceID: object['province_id'],
        cityID: object['city_id'],
        kecamatanID: object['kecamatan_id'],
        kelurahanID: object['kelurahan_id'],
        postalCodeID: object['postalcode_id'],
        addressProperty: object['addressproperty'],
        price: object['price'],
        isNego: object['isnego'],
        lebarjalandepan: object['lebarjalandepan'],
        luastanah: object['luastanah'],
        luasbangunan: object['luasbangunan'],
        statusKunciID: object['statuskunci_id'],
        bedroom: object['bedroom'],
        bathroom: object['bathroom'],
        maidBathroom: object['maidbathroom'],
        livingroom: object['livingroom'],
        dinningroom: object['dinningroom'],
        familyroom: object['familyroom'],
        kitchen: object['kitchen'],
        tamanDepan: object['tamandepan'],
        tamanBelakang: object['tamanbelakang'],
        furnitureID: object['furniture_id'],
        garageID: object['garage_id'],
        carportID: object['carport_id'],
        legalityID: object['legality_id'],
        fcLegalityID: object['fclegality_id'],
        listingStatusID: object['listingstatus_id'],
        useredited: object['useredited']);
  }

  static Future<InputListingModel> execAPIPost(
      String namepemilik,
      String noktppemilik,
      String addresspemilik,
      String phonepemilik,
      String workpemilik,
      String employeeID,
      String propertyID,
      String provinceID,
      String cityID,
      String kecamatanID,
      String kelurahanID,
      String postalCodeID,
      String addressProperty,
      String price,
      String isNego,
      String lebarjalandepan,
      String luastanah,
      String luasbangunan,
      String statusKunciID,
      String bedroom,
      String bathroom,
      String maidBathroom,
      String livingroom,
      String dinningroom,
      String familyroom,
      String kitchen,
      String tamanDepan,
      String tamanBelakang,
      String furnitureID,
      String garageID,
      String carportID,
      String legalityID,
      String fcLegalityID,
      String listingStatusID,
      String useredited) async {
    String apiURL = apiLink + '/Listing';

    var result = await http.post(apiURL, headers: {
      'Authorization': 'Basic ZVh0cm92ZXJ0Q29EZXY6bSFuIW00UDEyNw==',
      'xCdK3y5': 'P/Anp84aR046kFxcJolCn93b4UXNQ4moJ3DO6wqv'
    }, body: {
      'namepemilik': namepemilik,
      'noktppemilik': noktppemilik,
      'addresspemilik': addresspemilik,
      'phonepemilik': phonepemilik,
      'workpemilik': workpemilik,
      'employee_id': employeeID,
      'property_id': propertyID,
      'province_id': provinceID,
      'city_id': cityID,
      'kecamatan_id': kecamatanID,
      'kelurahan_id': kelurahanID,
      'postalcode_id': postalCodeID,
      'addressproperty': addressProperty,
      'price': price,
      'isnego': isNego,
      'lebarjalandepan': lebarjalandepan,
      'luastanah': luastanah,
      'luasbangunan': luasbangunan,
      'statuskunci_id': statusKunciID,
      'bedroom': bedroom,
      'bathroom': bathroom,
      'maidbathroom': maidBathroom,
      'livingroom': livingroom,
      'dinningroom': dinningroom,
      'familyroom': familyroom,
      'kitchen': kitchen,
      'tamandepan': tamanDepan,
      'tamanbelakang': tamanBelakang,
      'furniture_id': furnitureID,
      'garage_id': garageID,
      'carport_id': carportID,
      'legality_id': legalityID,
      'fclegality_id': fcLegalityID,
      'listingstatus_id': listingStatusID,
      'useredited': useredited
    });
    var jsonObject = jsonDecode(result.body);

    return InputListingModel.postInputListing(jsonObject);
  }
}
